trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.11'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r chapter-1/requirements.txt
  displayName: Install dependencies

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: chapter-1
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/app.zip

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appType: webAppLinux
    appName: 'vivekpythonproject'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'